apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |   
    server {
        listen 80;
        location / {
            proxy_pass http://duobackend:5500;
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: duofrontend
spec:
  type: LoadBalancer
  selector:
    app: duofrontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: duofrontend
  labels:
    app: duofrontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: duofrontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: duofrontend
    spec:
      containers:
      - name: duofrontend
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d
      volumes: 
      - name: nginx-config-volume
        configMap:
          name: nginx-config